name = "hono-cloudflare-backend"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
account_id = "fcd079bec6f835db7cba62fe47adc34c"

[build]
command = "npm run build"

[[migrations]]
tag = "v2"
deleted_classes = ["MetricsCollector"]

# Environment variables (optional)
# [vars]
# MY_VAR = "production"

# KV namespaces (optional)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects (optional)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# R2 buckets (optional)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Analytics Engine (for advanced monitoring)
# Uncomment and configure when you want to use Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "worker_analytics"

# Logpush configuration (optional)
# This helps with log aggregation and analysis
[observability]
enabled = true